"""
PubMed Search Agent Node — Performs PubMed/MEDLINE searches on the 3 treatment questions.

This LangGraph node takes the 3 treatment questions generated by the
classification agent, performs a PubMed search for each, and returns the
search context as a structured dictionary.

Runs in PARALLEL with the RAG agent in the pipeline.

Requirements:
    pip install biopython
"""

import os
import time
from typing import Any

from Bio import Entrez, Medline
from langchain_core.messages import AIMessage


# ── PubMed Config ──────────────────────────────────────────────────────
MAX_RESULTS_PER_QUERY = 3  # Number of PubMed articles per question
REQUEST_DELAY = 0.4  # seconds between requests (NCBI rate limit)

# NCBI Entrez requires an email for API usage
Entrez.email = os.getenv("PUBMED_EMAIL", "speech.agent@example.com")
Entrez.tool = "speech-agent"


def _pubmed_search(query: str, max_results: int = MAX_RESULTS_PER_QUERY) -> dict[str, Any]:
    """Search PubMed and return article IDs + metadata.

    Args:
        query: The search term (supports PubMed query syntax).
        max_results: Max number of results to return.

    Returns:
        Dictionary with 'count', 'ids', 'query_translation', and timing info.
    """
    search_params = {
        "db": "pubmed",
        "term": query,
        "retmax": max_results,
        "sort": "relevance",
        "retmode": "xml",
    }

    start = time.time()
    handle = Entrez.esearch(**search_params)
    record = Entrez.read(handle)
    handle.close()
    elapsed = time.time() - start

    return {
        "count": int(record.get("Count", 0)),
        "ids": list(record.get("IdList", [])),
        "query_translation": record.get("QueryTranslation", ""),
        "elapsed_seconds": round(elapsed, 3),
    }


def _fetch_article_details(pmids: list[str]) -> list[dict[str, Any]]:
    """Fetch detailed article metadata (title, abstract, authors, journal).

    Args:
        pmids: List of PubMed IDs to fetch.

    Returns:
        List of article dictionaries with parsed fields.
    """
    if not pmids:
        return []

    handle = Entrez.efetch(
        db="pubmed",
        id=",".join(pmids),
        rettype="medline",
        retmode="text",
    )
    records = list(Medline.parse(handle))
    handle.close()

    articles = []
    for rec in records:
        articles.append({
            "pmid": rec.get("PMID", "N/A"),
            "title": rec.get("TI", "No title"),
            "authors": rec.get("AU", []),
            "journal": rec.get("JT", "Unknown journal"),
            "journal_abbrev": rec.get("TA", ""),
            "pub_date": rec.get("DP", "Unknown date"),
            "abstract": rec.get("AB", "(No abstract available)"),
            "mesh_terms": rec.get("MH", []),
            "publication_type": rec.get("PT", []),
        })
    return articles


def _format_article_for_context(article: dict) -> str:
    """Format a single PubMed article into a context string.

    Args:
        article: Article dictionary from _fetch_article_details.

    Returns:
        Formatted string suitable for injection into the synthesis pipeline.
    """
    authors_str = ", ".join(article["authors"][:3])
    if len(article["authors"]) > 3:
        authors_str += " et al."

    return (
        f"Title: {article['title']}\n"
        f"Authors: {authors_str}\n"
        f"Journal: {article['journal']} ({article['pub_date']})\n"
        f"PMID: {article['pmid']}\n"
        f"Abstract: {article['abstract']}\n"
    )


def _perform_search(query: str, max_results: int = MAX_RESULTS_PER_QUERY) -> str:
    """Perform a single PubMed search and return formatted results.

    Args:
        query: The search query string.
        max_results: Maximum number of results to return.

    Returns:
        A string containing the formatted PubMed search results.
    """
    try:
        search = _pubmed_search(query, max_results=max_results)
        if not search["ids"]:
            return "(No PubMed results found)"

        time.sleep(REQUEST_DELAY)  # Rate-limit politeness
        articles = _fetch_article_details(search["ids"])

        formatted = []
        for i, article in enumerate(articles, 1):
            formatted.append(
                f"--- PubMed Reference {i} ---\n"
                f"{_format_article_for_context(article)}"
            )
        return "\n".join(formatted)
    except Exception as e:
        return f"(PubMed search failed: {e})"


def _format_web_results(web_search_dict: dict) -> str:
    """Format the PubMed search results dictionary into a readable context string.

    Args:
        web_search_dict: Dictionary with question keys and search results.

    Returns:
        A formatted string with all PubMed search context.
    """
    formatted_parts = []
    for key, entry in web_search_dict.items():
        formatted_parts.append(
            f"--- PubMed Search: {entry['query']} ---\n"
            f"{entry['results']}\n"
        )
    return "\n".join(formatted_parts)


def web_search_node(state: dict) -> dict:
    """LangGraph node: PubMed Search Agent.

    Extracts the 3 treatment questions from the classification output
    and performs a PubMed search for each. Always runs in parallel with
    the RAG agent (not conditional on category).

    Args:
        state: The pipeline state dictionary containing treatment_questions.

    Returns:
        Updated state with web_search_context and web_search_summary.
    """
    treatment_questions = state.get("treatment_questions", [])
    ailment = state.get("ailment", "Unknown")
    category = state.get("category", "Unknown")

    print(f"\n{'─'*60}")
    print(f"📚 [PubMed Search Agent] Searching for {len(treatment_questions)} questions...")
    print(f"   Ailment: {ailment} | Category: {category}")

    # Build search queries by combining ailment context with each question
    web_search_dict = {}

    for i, question in enumerate(treatment_questions, 1):
        # Build a PubMed-friendly query with the ailment + category context
        search_query = f"{ailment} {category} therapy: {question}"

        print(f"   🔎 [{i}/{len(treatment_questions)}] Searching PubMed: \"{search_query[:70]}...\"")

        time.sleep(REQUEST_DELAY)  # Rate-limit between searches
        results = _perform_search(search_query)

        # Count actual results (not error messages)
        has_results = not results.startswith("(")
        result_count = results.count("PubMed Reference") if has_results else 0
        status = f"✅ {result_count} articles" if has_results else "⚠️  No results"
        print(f"      {status}")

        web_search_dict[f"question_{i}"] = {
            "query": search_query,
            "original_question": question,
            "results": results,
        }

    # Format all results into a single context string
    web_search_summary = _format_web_results(web_search_dict)

    print(f"   ✅ [PubMed Search Agent] Done! Summary: {len(web_search_summary)} chars")
    print(f"{'─'*60}\n")

    return {
        "web_search_context": web_search_dict,
        "web_search_summary": web_search_summary,
        "messages": [
            AIMessage(
                content=f"PubMed search completed for {len(treatment_questions)} questions."
            )
        ],
    }
