"""
Web Search Agent Node — Performs web searches on the 3 treatment questions.

This LangGraph node takes the 3 treatment questions generated by the
classification agent, performs a web search for each, and returns the
search context as a structured dictionary.

Runs in PARALLEL with the RAG agent in the pipeline.
"""

import warnings
warnings.filterwarnings("ignore", message=".*duckduckgo_search.*renamed.*")

from duckduckgo_search import DDGS
from langchain_core.messages import AIMessage


# ── Search Config ──────────────────────────────────────────────────────
MAX_RESULTS_PER_QUERY = 3  # Number of search results per question


def _perform_search(query: str, max_results: int = MAX_RESULTS_PER_QUERY) -> str:
    """Perform a single web search using DuckDuckGo.

    Args:
        query: The search query string.
        max_results: Maximum number of results to return.

    Returns:
        A string containing the formatted search results.
    """
    try:
        with DDGS() as ddgs:
            results = list(ddgs.text(query, max_results=max_results))
        if not results:
            return "(No results found)"

        formatted = []
        for i, r in enumerate(results, 1):
            formatted.append(
                f"[{i}] {r.get('title', 'No title')}\n"
                f"    URL: {r.get('href', 'N/A')}\n"
                f"    {r.get('body', 'No snippet')}"
            )
        return "\n".join(formatted)
    except Exception as e:
        return f"(Search failed: {e})"


def _format_web_results(web_search_dict: dict) -> str:
    """Format the web search results dictionary into a readable context string.

    Args:
        web_search_dict: Dictionary with question keys and search results.

    Returns:
        A formatted string with all web search context.
    """
    formatted_parts = []
    for key, entry in web_search_dict.items():
        formatted_parts.append(
            f"--- Web Search: {entry['query']} ---\n"
            f"{entry['results']}\n"
        )
    return "\n".join(formatted_parts)


def web_search_node(state: dict) -> dict:
    """LangGraph node: Web Search Agent.

    Extracts the 3 treatment questions from the classification output
    and performs a web search for each. Always runs in parallel with
    the RAG agent (not conditional on category).

    Args:
        state: The pipeline state dictionary containing treatment_questions.

    Returns:
        Updated state with web_search_context and web_search_summary.
    """
    treatment_questions = state.get("treatment_questions", [])
    ailment = state.get("ailment", "Unknown")
    category = state.get("category", "Unknown")

    print(f"\n{'─'*60}")
    print(f"🌐 [Web Search Agent] Searching for {len(treatment_questions)} questions...")
    print(f"   Ailment: {ailment} | Category: {category}")

    # Build search queries by combining ailment context with each question
    web_search_dict = {}

    for i, question in enumerate(treatment_questions, 1):
        # Enrich the question with ailment context for better search results
        search_query = f"{ailment} {category} therapy: {question}"

        print(f"   🔎 [{i}/{len(treatment_questions)}] Searching: \"{search_query[:70]}...\"")
        results = _perform_search(search_query)

        # Count actual results (not error messages)
        has_results = not results.startswith("(")
        result_count = results.count("[") if has_results else 0
        status = f"✅ {result_count} results" if has_results else "⚠️  No results"
        print(f"      {status}")

        web_search_dict[f"question_{i}"] = {
            "query": search_query,
            "original_question": question,
            "results": results,
        }

    # Format all results into a single context string
    web_search_summary = _format_web_results(web_search_dict)

    print(f"   ✅ [Web Search Agent] Done! Summary: {len(web_search_summary)} chars")
    print(f"{'─'*60}\n")

    return {
        "web_search_context": web_search_dict,
        "web_search_summary": web_search_summary,
        "messages": [
            AIMessage(
                content=f"Web search completed for {len(treatment_questions)} questions."
            )
        ],
    }
